[package]
name = "keipes-ai-mcp"
version = "0.1.0"
edition = "2021"

[dependencies]
rmcp = { version = "0.3", features = [
    "server",
    "transport-streamable-http-server",
    "transport-worker",
    "macros",
] }
rmcp-macros = "0.3"
tokio = { version = "1.0", features = ["full"] }
tokio-util = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
axum = "0.8"
uuid = { version = "1.0", features = ["v4"] }
bf2042_stats = { git = "https://github.com/keipes/keipes-ai-mcp-2042" }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lib]
name = "keipes_ai_mcp"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dev-dependencies]
anyhow = "1.0"
reqwest = { version = "0.12", features = ["json"] }
