version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: keipes-postgres
    environment:
      POSTGRES_DB: keipes_mcp
      POSTGRES_USER: keipes
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keipes -d keipes_mcp"]
      interval: 10s
      timeout: 5s
      retries: 5

  keipes-ai-mcp:
    build: .
    container_name: keipes-mcp-server
    ports:
      - "8000:80"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://keipes:password@postgres:5432/keipes_mcp
    restart: unless-stopped

volumes:
  postgres_data:
