version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: keipes-postgres
    environment:
      POSTGRES_DB: keipes_mcp
      POSTGRES_USER: keipes
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keipes -d keipes_mcp"]
      interval: 10s
      timeout: 5s
      retries: 5

  keipes-ai-mcp:
    build: .
    container_name: keipes-mcp-server
    expose:
      - "80"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://keipes:password@postgres:5432/keipes_mcp
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: keipes-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_www:/var/www/certbot:ro
      - certbot_ssl:/etc/letsencrypt:ro
    depends_on:
      - keipes-ai-mcp
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: keipes-certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_ssl:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email keithpsmith@gmail.com --agree-tos --no-eff-email -d mcp-origin.driveways.lol
    depends_on:
      - nginx

volumes:
  postgres_data:
  certbot_www:
  certbot_ssl:
